import os

# Bot Configuration
TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
DIGIFLAZZ_USERNAME = os.getenv("DIGIFLAZZ_USERNAME")
DIGIFLAZZ_KEY = os.getenv("DIGIFLAZZ_KEY")
ADMIN_IDS = [int(x) for x in os.getenv("ADMIN_IDS", "7044289974").split(",")]

# Digiflazz API URLs
DIGIFLAZZ_BASE_URL = "https://api.digiflazz.com/v1"
DIGIFLAZZ_PRICELIST_URL = f"{DIGIFLAZZ_BASE_URL}/price-list"
DIGIFLAZZ_TRANSACTION_URL = f"{DIGIFLAZZ_BASE_URL}/transaction"

# Database Configuration
DATABASE_FILE = "bot_database.db"

# Conversation States
(MENU_UTAMA, ADMIN_MENU, DEPOSIT_FLOW, CONFIRM_DEPOSIT_FLOW, 
 BUY_FLOW, TRANSACTION_ID_FLOW, ADMIN_DELETE_PRODUCT_FLOW, 
 ADMIN_MANAGE_FLOW, WAITING_TARGET_ID, CONFIRMING_PURCHASE,
 WAITING_DEPOSIT_AMOUNT, WAITING_DEPOSIT_PROOF, ADMIN_CONFIRM_DEPOSIT) = range(13)
